trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  npm_config_cache: '$(Pipeline.Workspace)/.npm'

steps:
  - checkout: self
    persistCredentials: true
  
  # - task: CmdLine@2
  #   displayName: Checkout $(Build.SourceBranchName)
  #   inputs:
  #     script: 'git checkout $(Build.SourceBranchName)'

  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: Install Node.js
    
  - task: Bash@3
    displayName: Install global dependency
    inputs:
      targetType: inline
      script: |
        sudo npm install -g typescript
        sudo npm install -g ts-node
  
  - task: Npm@1
    inputs:
      command: install
      verbose: true
    displayName: Install dependencies
  # - task: Cache@2
  #   inputs:
  #     key: 'npm | "$(Agent.OS)" | package-lock.json'
  #     path: $(npm_config_cache)
  #   displayName: Cache npm

  - task: Bash@3
    displayName: Set git config
    inputs:
      targetType: inline
      script: |
        git config --global user.email "bot@trustwallet.com"
        git config --global user.name "TrustWalletBot"
      

  - script: sudo npm run checksum
    workingDirectory: $(Build.SourcesDirectory)
    displayName: Run checksum script

  - task: Bash@3
    displayName: Commit result of checksum script
    inputs:
      targetType: filePath
      filePath: ./script/commit.sh
    
  - script: npm t
    displayName: Run tests