trigger:
    - master

pool:
    vmImage: 'ubuntu-latest'

variables:
    npm_config_cache: '$(Pipeline.Workspace)/.npm'

steps:
    # - task: NodeTool@0
    #   inputs:
    #     versionSpec: '12.x'
    #   displayName: Install Node.js
    - script: |
        curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
        sudo apt-get install -y nodejs
      displayName: Install Node 10
      
    - script: |
        sudo npm install -g typescript
        sudo npm install -g ts-node
      displayName: Install global dependency

    - script: npm install
      displayName: Install project dependencies
    
    # - task: Cache@2
    #   inputs:
    #     key: 'npm | "$(Agent.OS)" | package-lock.json'
    #     path: $(npm_config_cache)
    #   displayName: Cache npm
    
    - script: |
        git config --global user.email "bot@trustwallet.com"
        git config --global user.name "TrustWalletBot"

    - checkout: self
      persistCredentials: true

    - script: npm run checksum-erc20

    - bash: './script/commit.sh'
      
    - script: npm t