name: Periodic External Update
on:
  schedule:
    # Run twice per day (at 7:00UTC/12amPST, 19:00UTC/12pmPST)
    - cron:  '0 7,19 * * *'
jobs:
  scripts:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
         token: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
         ref: ${{ github.head_ref }} 
     - uses: actions/setup-node@v1
       with:
         node-version: 12
     - name: Install Dependencies
       run: npm ci
     - name: Run scripts
       run: npm run update
     - name: Show fix result (diff); run 'npm run fix' locally
       if: success()
       run: git status
     - name: Run check
       run: npm run check
     - name: Run test
       run: npm t
     - name: Commit changes test pased
       if: success()
       uses: stefanzweifel/git-auto-commit-action@v4.1.2
       with:
         commit_user_name: trust-wallet-merge-bot
         commit_user_email: mergebot@trustwallet.com
         commit_message: External Updates
